openapi: 3.0.0
info:
  contact:
    email: apisupport@zenoti.com
  description: |+
    Our API documentation has been moved to https://docs.zenoti.com. 

  termsOfService: ''
  title: Zenoti API
  version: 1.0.0
servers:
  - url: 'https://api.zenoti.com/'
security:
  - API_Key: []

