openapi: 3.0.0
info:
  termsOfService: https://fungenerators.com/terms
  description: >
    Ahoy matey! We help the landlubbers to get to know about the seamen way! You can generate pirate names, get some real pirate insults and pirate filler text. Oh you can translate to pirate lingo as well. [Click here to subscribe](http://fungenerators.com/products/documentation/pirate/) 
  title: Pirates API
  version: "1.5"
  contact:
    name: Fun Generators
    url: http://fungenerators.com/api/pirate/
tags:
  - name: Generation
    description: Generate names, insults, lorem ipsum etc 
    externalDocs:
      description: Find out more
      url: http://fungenerators.com/api/pirate/
  - name: Translation
    description: Translate to pirate lingo
    externalDocs:
      description: Find out more
      url: http://fungenerators.com/api/pirate/      
paths:
  /pirate/generate/name:
    get:
      tags:
        - Generation
      description: Generate random pirate names.
      security:
        - X-Fungenerators-Api-Secret: []
      parameters:
        - description: Variation to generate `male/female`.
          in: query
          name: variation
          required: false
          schema:
            type: string
            format: string
        - description: No of names to generate
          in: query
          name: limit
          required: false
          schema:
            type: integer
            format: integer            
      responses:
        "200":
          description: 200  response
          content:
            application/json:
              examples:
                response:
                  value: |-
                      {
                        "success": {
                          "total": 5,
                          "start": 0,
                          "limit": 5
                        },
                        "contents": {
                          "variation": "male",
                          "names": [
                            "Mabry 'Devil's Smile' Hades",
                            "Rae 'The Wrath' Rakshasas",
                            "Thorndike 'Merry' Tyndall",
                            "Crofton 'The Lion' Dante",
                            "Southwell 'Squealer' Sweete"
                          ]
                        },
                        "copyright": "https://fungenerators.com/"
                      }
        "401":
          description: 401  response
          content:
            application/json:
              examples:
                response:
                  value: |-
                    {
                        "error": {
                            "code": 401,
                            "message": "Unauthorized"
                        }
                    }
  /pirate/generate/insult:
    get:
      tags:
        - Generation
      description: Generate random pirate insults.
      security:
        - X-Fungenerators-Api-Secret: []
      parameters:
        - description: No of insults to generate
          in: query
          name: limit
          required: false
          schema:
            type: integer
            format: integer   
      responses:
        "200":
          description: 200  response
          content:
            application/json:
              examples:
                response:
                  value: |-
                        {
                          "success": {
                            "total": 5,
                            "limit": 5
                          },
                          "contents": {
                            "taunts": [
                              "It's all great fun 'til somebody loses an eye! ye swashbucklin' deck-swabbing Orlop!",
                              "Go pose in front o' the mirror some more plait bearded dung munchin Duffle!",
                              "Kill my parrot will ye? I'm gonna knot yer legs together ye  loot-stealing narwhal-smelling bat-spit!",
                              "Welcome to PAIN TIME with a Pirate! Starring YOU! ye squiffy deck-swabbing bilge rat!",
                              "Blow it out yer bilge! ye rat-eating grog-drinking Jolly Roger!"
                            ]
                          },
                          "copyright": "https://fungenerators.com/"
                        }
        "401":
          description: 401  response
          content:
            application/json:
              examples:
                response:
                  value: |-
                    {
                        "error": {
                            "code": 401,
                            "message": "Unauthorized"
                        }
                    }                    
  /pirate/generate/lorem-ipsum:
    get:
      tags:
        - Generation
      description: Generate pirate lorem ipsum.
      security:
        - X-Fungenerators-Api-Secret: []
      parameters:
        - description: Type of element to generate `paragraphs/sentences/words`.
          in: query
          name: type
          required: false
          schema:
            type: string
            format: string
        - description: No of elements to generate
          in: query
          name: limit
          required: false
          schema:
            type: integer
            format: integer           
      responses:
        "200":
          description: 200  response
          content:
            application/json:
              examples:
                response:
                  value: |-
                      {
                        "success": {
                          "total": 4,
                          "limit": 4
                        },
                        "contents": {
                          "lorem-ipsum": "[\"Wanna shiver me timbers? \\u201cI\\u2019ve got a jar of dirt! I\\u2019ve got a jar of dirt, and guess what\\u2019s inside it?\\u201d \\u201cWhy is the rum always gone?\\u201d \\u201cYes, I do heartily repent. I repent I had not done more mischief; and that we did not cut the throats of them that took us, and I am extremely sorry that you aren\\u2019t hanged as well as we. \\u201d It is when pirates count their booty that they become mere thieves. Arrrrrrrr Piracy \\u2013 Hostile take over.\",\"Avast, me proud beauty! Wanna know why my Roger is so Jolly?  Ya know, darlin\\u2019, I\\u2019m 97 percent chum free Wanna shiver me timbers? Give me freedom or give me the rope. For I shall not take the shackles that subjugate the poor to uphold the rich. \\u201cYes, I do heartily repent. I repent I had not done more mischief; and that we did not cut the throats of them that took us, and I am extremely sorry that you aren\\u2019t hanged as well as we. \\u201d But I am touched by y\\u2019loyalty mate. Piracy \\u2013 Hostile take over.\",\"How\\u2019d you like to scrape the barnacles off of me rudder? That\\u2019s the finest pirate booty I\\u2019ve ever laid eyes on. C\\u2019mon, lad, shiver me timbers! To err is human but to arr is pirate!!\",\"Yes, that is a hornpipe in my pocket and I am happy to see you. Aye, I guarantee ye, I\\u2019ve had a twenty percent decrease in me \\u201clice ratio!\\u201d Why is the rum gone? Drink up me hearties yoho \\u2026a pirates life for me Where there is a sea there are pirates. \\u201cYes, I do heartily repent. I repent I had not done more mischief; and that we did not cut the throats of them that took us, and I am extremely sorry that you aren\\u2019t hanged as well as we. \\u201d\"]"
                        },
                        "copyright": "https://fungenerators.com/"
                      }
        "401":
          description: 401  response
          content:
            application/json:
              examples:
                response:
                  value: |-
                    {
                        "error": {
                            "code": 401,
                            "message": "Unauthorized"
                        }
                    }                    
  /pirate/translate: 
    get:
      tags:
        - Translation
      description: Translate from English to pirate.
      security:
        - X-Fungenerators-Api-Secret: []
      parameters:
        - description: Text to translate to pirate lingo.
          in: query
          name: text
          required: true
          schema:
            type: string
            format: string
      responses:
        "200":
          description: 200  response
          content:
            application/json:
              examples:
                response:
                  value: |-
                    {
                      "success": {
                        "total": 1
                      },
                      "contents": {
                        "translated": "Ahoy matey!  Splice the mainbrace! me dear ol' mum, bless her black soul goes with me t' th' briny deep.",
                        "text": "Hello sir! my mother goes with me to the ocean."
                      },
                      "copyright": "https://fungenerators.com/"
                    }
        "401":
          description: 401  response
          content:
            application/json:
              examples:
                response:
                  value: |-
                    {
                        "error": {
                            "code": 401,
                            "message": "Unauthorized"
                        }
                    }       
servers:
  - url: https://api.fungenerators.com
components:
  securitySchemes:
    X-Fungenerators-Api-Secret:
      type: apiKey
      name: X-Fungenerators-Api-Secret
      in: header

