openapi: 3.0.0
info:
  description: The HDInsight Management Client.
  title: HDInsightManagementClient
  version: 2015-03-01-preview
servers:
  - url: 'https://management.azure.com/'
paths:
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HDInsight/clusters/{clusterName}/applications':
    get:
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ResourceGroupNameParameter'
        - $ref: '#/components/parameters/ClusterNameParameter'
        - $ref: '#/components/parameters/ApiVersionParameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationListResult'
          description: OK. The request has succeeded.
        default:
          content:
            application/json:
              schema:
                $ref: ./operations.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - Applications
      description: Lists all of the applications for the HDInsight cluster.
      operationId: Applications_List
      x-ms-examples:
        Get All Applications for an HDInsight cluster:
          $ref: ./examples/GetAllApplications.json
      x-ms-pageable:
        nextLinkName: nextLink
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HDInsight/clusters/{clusterName}/applications/{applicationName}':
    delete:
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ResourceGroupNameParameter'
        - $ref: '#/components/parameters/ClusterNameParameter'
        - $ref: '#/components/parameters/ApplicationNameParameter'
        - $ref: '#/components/parameters/ApiVersionParameter'
      responses:
        '200':
          description: OK. The request has succeeded.
        '202':
          description: Accepted response definition.
        '204':
          description: No Content response definition.
        default:
          content:
            application/json:
              schema:
                $ref: ./operations.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - Applications
      description: Deletes the specified application on the HDInsight cluster.
      operationId: Applications_Delete
      x-ms-examples:
        Delete Application from HDInsight cluster:
          $ref: ./examples/DeleteApplication.json
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
    get:
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ResourceGroupNameParameter'
        - $ref: '#/components/parameters/ClusterNameParameter'
        - $ref: '#/components/parameters/ApplicationNameParameter'
        - $ref: '#/components/parameters/ApiVersionParameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
          description: OK. The request has succeeded.
        default:
          content:
            application/json:
              schema:
                $ref: ./operations.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - Applications
      description: Lists properties of the specified application.
      operationId: Applications_Get
      x-ms-examples:
        Get application on HDInsight cluster creation in progress:
          $ref: ./examples/GetApplicationInProgress.json
        Get application on HDInsight cluster successfully created.:
          $ref: ./examples/GetApplicationCreated.json
    put:
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ResourceGroupNameParameter'
        - $ref: '#/components/parameters/ClusterNameParameter'
        - $ref: '#/components/parameters/ApplicationNameParameter'
        - $ref: '#/components/parameters/ApiVersionParameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
          description: OK. The request has succeeded.
        default:
          content:
            application/json:
              schema:
                $ref: ./operations.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - Applications
      description: Creates applications for the HDInsight cluster.
      operationId: Applications_Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
        description: The application create request.
        required: true
      x-ms-examples:
        Create Application:
          $ref: ./examples/CreateApplication.json
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HDInsight/clusters/{clusterName}/applications/{applicationName}/azureasyncoperations/{operationId}':
    get:
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ResourceGroupNameParameter'
        - $ref: '#/components/parameters/ClusterNameParameter'
        - $ref: '#/components/parameters/ApplicationNameParameter'
        - $ref: '#/components/parameters/ApiVersionParameter'
        - $ref: '#/components/parameters/OperationIdParameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ./cluster.json#/definitions/AsyncOperationResult
          description: OK response definition.
        default:
          content:
            application/json:
              schema:
                $ref: ./operations.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - Applications
      description: Gets the async operation status.
      operationId: Applications_GetAzureAsyncOperationStatus
      x-ms-examples:
        Get the azure async operation status.:
          $ref: ./examples/GetApplicationCreationAsyncOperationStatus.json
components:
  parameters:
    ApiVersionParameter:
      description: The HDInsight client API Version.
      in: query
      name: api-version
      required: true
      schema:
        type: string
    ApplicationNameParameter:
      description: The constant value for the application name.
      in: path
      name: applicationName
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    ClusterNameParameter:
      description: The name of the cluster.
      in: path
      name: clusterName
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    OperationIdParameter:
      description: The long running operation id.
      in: path
      name: operationId
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    ResourceGroupNameParameter:
      description: The name of the resource group.
      in: path
      name: resourceGroupName
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    SubscriptionIdParameter:
      description: >-
        The subscription credentials which uniquely identify Microsoft Azure
        subscription. The subscription ID forms part of the URI for every
        service call.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
  schemas:
    Application:
      allOf:
        - $ref: ./cluster.json#/definitions/ProxyResource
      description: The HDInsight cluster application
      properties:
        tags:
          additionalProperties:
            type: string
          description: The tags for the application.
          type: object
        etag:
          description: The ETag for the application
          type: string
        properties:
          $ref: '#/components/schemas/ApplicationProperties'
          description: The properties of the application.
      type: object
    ApplicationGetEndpoint:
      description: Gets the application SSH endpoint
      properties:
        destinationPort:
          description: The destination port to connect to.
          format: int32
          type: integer
        location:
          description: The location of the endpoint.
          type: string
        privateIPAddress:
          description: The private ip address of the endpoint.
          type: string
        publicPort:
          description: The public port to connect to.
          format: int32
          type: integer
      type: object
    ApplicationGetHttpsEndpoint:
      description: Gets the application HTTP endpoints.
      properties:
        accessModes:
          description: The list of access modes for the application.
          items:
            type: string
          type: array
        destinationPort:
          description: The destination port to connect to.
          format: int32
          type: integer
        disableGatewayAuth:
          description: The value indicates whether to disable GatewayAuth.
          type: boolean
          x-ms-mutability:
            - create
            - update
        location:
          description: The location of the endpoint.
          readOnly: true
          type: string
        privateIPAddress:
          description: The private ip address of the endpoint.
          type: string
        publicPort:
          description: The public port to connect to.
          format: int32
          readOnly: true
          type: integer
        subDomainSuffix:
          description: The subdomain suffix of the application.
          type: string
          x-ms-mutability:
            - create
            - update
      type: object
    ApplicationListResult:
      description: >-
        Result of the request to list cluster Applications. It contains a list
        of operations and a URL link to get the next set of results.
      properties:
        nextLink:
          description: >-
            The URL to get the next set of operation list results if there are
            any.
          readOnly: true
          type: string
        value:
          description: The list of HDInsight applications installed on HDInsight cluster.
          items:
            $ref: '#/components/schemas/Application'
          type: array
      type: object
    ApplicationProperties:
      description: The HDInsight cluster application GET response.
      properties:
        applicationState:
          description: The application state.
          readOnly: true
          type: string
        applicationType:
          description: The application type.
          type: string
        computeProfile:
          $ref: ./cluster.json#/definitions/ComputeProfile
          description: The list of roles in the cluster.
        createdDate:
          description: The application create date time.
          readOnly: true
          type: string
        errors:
          description: The list of errors.
          items:
            $ref: ./cluster.json#/definitions/Errors
          type: array
        httpsEndpoints:
          description: The list of application HTTPS endpoints.
          items:
            $ref: '#/components/schemas/ApplicationGetHttpsEndpoint'
          type: array
        installScriptActions:
          description: The list of install script actions.
          items:
            $ref: ./cluster.json#/definitions/RuntimeScriptAction
          type: array
        marketplaceIdentifier:
          description: The marketplace identifier.
          readOnly: true
          type: string
        provisioningState:
          description: The provisioning state of the application.
          readOnly: true
          type: string
        sshEndpoints:
          description: The list of application SSH endpoints.
          items:
            $ref: '#/components/schemas/ApplicationGetEndpoint'
          type: array
        uninstallScriptActions:
          description: The list of uninstall script actions.
          items:
            $ref: ./cluster.json#/definitions/RuntimeScriptAction
          type: array
      type: object
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      flows:
        implicit:
          authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/authorize'
          scopes:
            user_impersonation: impersonate your user account
      type: oauth2
security:
  - azure_auth:
      - user_impersonation

