openapi: 3.0.0
info:
  description: >-
    Use these REST APIs for performing operations on Backend entity in Azure API
    Management deployment. The Backend entity in API Management represents a
    backend service that is configured to skip certification chain validation
    when using a self-signed certificate to test mutual certificate
    authentication.
  title: ApiManagementClient
  version: '2017-03-01'
servers:
  - url: '{apimBaseUrl}'
    variables:
      apimBaseUrl:
        default: ''
        description: >-
          The management endpoint of the API Management service, for example
          https://myapimservice.management.azure-api.net.
        x-ms-skip-url-encoding: true
paths:
  /backends:
    get:
      parameters:
        - description: >-
            | Field | Supported operators    | Supported
            functions                         |

            |-------|------------------------|---------------------------------------------|

            | id    | ge, le, eq, ne, gt, lt | substringof, contains,
            startswith, endswith |

            | host  | ge, le, eq, ne, gt, lt | substringof, contains,
            startswith, endswith |
          in: query
          name: $filter
          required: false
          schema:
            type: string
        - $ref: ./apimanagement.json#/components/parameters/TopQueryParameter
        - $ref: ./apimanagement.json#/components/parameters/SkipQueryParameter
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackendCollection'
          description: Lists a collection of Backend entities.
        default:
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - Backends
      description: Lists a collection of backends in the specified service instance.
      operationId: Backend_List
      x-ms-examples:
        ApiManagementListBackends:
          $ref: ./examples/ApiManagementListBackends.json
      x-ms-odata: '#/components/schemas/BackendContract'
      x-ms-pageable:
        nextLinkName: nextLink
  '/backends/{backendid}':
    delete:
      parameters:
        - $ref: '#/components/parameters/BackendIdParameter'
        - description: >-
            The entity state (Etag) version of the backend to delete. A value of
            "*" can be used for If-Match to unconditionally apply the operation.
          in: header
          name: If-Match
          required: true
          schema:
            type: string
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        '204':
          description: The backend was successfully deleted.
        default:
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - Backends
      description: Deletes the specified backend.
      operationId: Backend_Delete
      x-ms-examples:
        ApiManagementDeleteBackends:
          $ref: ./examples/ApiManagementDeleteBackends.json
    get:
      parameters:
        - $ref: '#/components/parameters/BackendIdParameter'
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackendContract'
          description: The response body contains the specified Backend entity.
          headers:
            ETag:
              description: >-
                Current entity state version. Should be treated as opaque and
                used to make conditional HTTP requests.
              schema:
                type: string
        default:
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - Backends
      description: Gets the details of the backend specified by its identifier.
      operationId: Backend_Get
      x-ms-examples:
        ApiManagementGetBackends:
          $ref: ./examples/ApiManagementGetBackends.json
    patch:
      parameters:
        - $ref: '#/components/parameters/BackendIdParameter'
        - description: >-
            The entity state (Etag) version of the backend to update. A value of
            "*" can be used for If-Match to unconditionally apply the operation.
          in: header
          name: If-Match
          required: true
          schema:
            type: string
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        '204':
          description: The existing backend was successfully updated.
        default:
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - Backends
      description: Updates an existing backend.
      operationId: Backend_Update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackendUpdateParameters'
        description: Update parameters.
        required: true
      x-ms-examples:
        ApiManagementPatchBackends:
          $ref: ./examples/ApiManagementPatchBackends.json
    put:
      parameters:
        - $ref: '#/components/parameters/BackendIdParameter'
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackendContract'
          description: The existing backend was successfully updated.
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackendContract'
          description: Backend was successfully created.
        default:
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - Backends
      description: Creates or Updates a backend.
      operationId: Backend_CreateOrUpdate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackendContract'
        description: Create parameters.
        required: true
      x-ms-examples:
        ApiManagementPutBackends:
          $ref: ./examples/ApiManagementPutBackends.json
components:
  parameters:
    BackendIdParameter:
      description: >-
        Identifier of the Backend entity. Must be unique in the current API
        Management service instance.
      in: path
      name: backendid
      required: true
      schema:
        maxLength: 255
        minLength: 1
        pattern: '^[^*#&+:<>?]+$'
        type: string
      x-ms-parameter-location: method
  schemas:
    BackendAuthorizationHeaderCredentials:
      description: Authorization header information.
      properties:
        parameter:
          description: Authentication Parameter value.
          maxLength: 300
          minLength: 1
          type: string
        scheme:
          description: Authentication Scheme name.
          maxLength: 100
          minLength: 1
          type: string
      required:
        - scheme
        - parameter
      type: object
    BackendBaseParameters:
      description: Backend entity base Parameter set.
      properties:
        credentials:
          $ref: '#/components/schemas/BackendCredentialsContract'
          description: Backend Credentials Contract Properties
        description:
          description: Backend Description.
          maxLength: 2000
          minLength: 1
          type: string
        properties:
          $ref: '#/components/schemas/BackendProperties'
          description: Backend Properties contract
        proxy:
          $ref: '#/components/schemas/BackendProxyContract'
          description: Backend Proxy Contract Properties
        resourceId:
          description: >-
            Management Uri of the Resource in External System. This url can be
            the Arm Resource Id of Logic Apps, Function Apps or Api Apps.
          maxLength: 2000
          minLength: 1
          type: string
        title:
          description: Backend Title.
          maxLength: 300
          minLength: 1
          type: string
        tls:
          $ref: '#/components/schemas/BackendTlsProperties'
          description: Backend TLS Properties
      type: object
    BackendCollection:
      description: Paged Backend list representation.
      properties:
        count:
          description: Total number of entities
          type: integer
        nextLink:
          description: Next page link if any.
          type: string
        value:
          description: Backend values.
          items:
            $ref: '#/components/schemas/BackendContract'
          type: array
      type: object
    BackendContract:
      allOf:
        - $ref: '#/components/schemas/BackendContractProperties'
      description: Backend details.
      properties:
        id:
          description: Identifier of the Backend entity.
          type: string
      type: object
    BackendContractProperties:
      allOf:
        - $ref: '#/components/schemas/BackendBaseParameters'
      description: Parameters supplied to the Create Backend operation.
      properties:
        protocol:
          description: Backend communication protocol.
          enum:
            - http
            - soap
          type: string
          x-ms-enum:
            modelAsString: true
            name: BackendProtocol
            values:
              - description: The Backend is a RESTful service.
                value: http
              - description: The Backend is a SOAP service.
                value: soap
        url:
          description: Runtime Url of the Backend.
          maxLength: 2000
          minLength: 1
          type: string
      required:
        - url
        - protocol
      type: object
    BackendCredentialsContract:
      description: Details of the Credentials used to connect to Backend.
      properties:
        authorization:
          $ref: '#/components/schemas/BackendAuthorizationHeaderCredentials'
          description: Authorization header authentication
        certificate:
          description: List of Client Certificate Thumbprint.
          items:
            type: string
          maxItems: 32
          type: array
        header:
          additionalProperties:
            items:
              type: string
            type: array
          description: Header Parameter description.
          type: object
        query:
          additionalProperties:
            items:
              type: string
            type: array
          description: Query Parameter description.
          type: object
      type: object
    BackendProperties:
      description: Properties specific to the Backend Type.
      properties:
        serviceFabricCluster:
          $ref: '#/components/schemas/BackendServiceFabricClusterProperties'
          description: Backend Service Fabric Cluster Properties
      type: object
    BackendProxyContract:
      externalDocs:
        description: Backend entity uses these details to connect to a WebProxy.
        url: >-
          https://msdn.microsoft.com/en-us/library/system.net.webproxy(v=vs.110).aspx
      description: Details of the Backend WebProxy Server to use in the Request to Backend.
      properties:
        password:
          description: Password to connect to the WebProxy Server
          type: string
        url:
          description: >-
            WebProxy Server AbsoluteUri property which includes the entire URI
            stored in the Uri instance, including all fragments and query
            strings.
          maxLength: 2000
          minLength: 1
          type: string
        username:
          description: Username to connect to the WebProxy server
          type: string
      required:
        - url
      type: object
    BackendServiceFabricClusterProperties:
      description: Properties of the Service Fabric Type Backend.
      properties:
        clientCertificateThumbprint:
          description: The client certificate thumbprint for the management endpoint.
          type: string
        managementEndpoints:
          description: The cluster management endpoint.
          items:
            type: string
          type: array
        maxPartitionResolutionRetries:
          description: Maximum number of retries while attempting resolve the partition.
          format: int32
          type: integer
        partitionResolutionRequestTimeout:
          description: >-
            Maximum time allowed to update partition resolution data. Duration
            needs to be specified using the format PT[n]H[n]M[n]S as per ISO8601
          format: duration
          type: string
        serverCertificateThumbprints:
          description: >-
            Thumbprints of certificates cluster management service uses for tls
            communication
          items:
            type: string
          type: array
        serverX509Names:
          description: Server X509 Certificate Names Collection
          items:
            $ref: '#/components/schemas/X509CertificateName'
          type: array
      required:
        - managementEndpoints
        - clientCertificateThumbprint
      type: object
    BackendTlsProperties:
      description: Properties controlling TLS Certificate Validation.
      properties:
        validateCertificateChain:
          default: true
          description: >-
            Flag indicating whether SSL certificate chain validation should be
            done when using self-signed certificates for this backend host.
          type: boolean
        validateCertificateName:
          default: true
          description: >-
            Flag indicating whether SSL certificate name validation should be
            done when using self-signed certificates for this backend host.
          type: boolean
      type: object
    BackendUpdateParameters:
      allOf:
        - $ref: '#/components/schemas/BackendBaseParameters'
      description: Parameters supplied to the Update Backend operation.
      properties:
        protocol:
          description: Backend communication protocol.
          enum:
            - http
            - soap
          type: string
          x-ms-enum:
            modelAsString: true
            name: BackendProtocol
            values:
              - description: The Backend is a RESTful service.
                value: http
              - description: The Backend is a SOAP service.
                value: soap
        url:
          description: Runtime Url of the Backend.
          maxLength: 2000
          minLength: 1
          type: string
      type: object
    X509CertificateName:
      externalDocs:
        url: >-
          https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-windows-cluster-x509-security
      description: Properties of server X509Names.
      properties:
        issuerCertificateThumbprint:
          description: Thumbprint for the Issuer of the Certificate.
          type: string
        name:
          description: Common Name of the Certificate.
          type: string
      type: object
  securitySchemes:
    apim_key:
      in: header
      name: Authorization
      type: apiKey
security:
  - apim_key: []

