openapi: 3.0.0
info:
  contact:
    email: hello@poemist.com
    name: Poemist Team
    url: 'https://www.poemist.com'
  title: Poemist API
  version: '1.0'
  x-logo:
    url: 'https://www.poemist.com/images/logo.png'
servers:
  - url: 'https://www.poemist.com/api/v1/'
paths:
  /randompoems:
    get:
      responses:
        '200':
          description: Random poems to be returned
      operationId: randompoems

