openapi: 3.0.0
info:
  description: >-
    API spec for Microsoft.Security (Microsoft Defender for Cloud) resource
    provider
  title: Microsoft Defender for Cloud
  version: 2015-06-01-preview
servers:
  - url: 'https://management.azure.com/'
paths:
  '/subscriptions/{subscriptionId}/providers/Microsoft.Security/applicationWhitelistings':
    get:
      parameters:
        - $ref: ../../../common/v1/types.json#/components/parameters/SubscriptionId
        - $ref: ../../../common/v1/types.json#/components/parameters/ApiVersion
        - $ref: '#/components/parameters/IncludePathRecommendations'
        - $ref: '#/components/parameters/Summary'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppWhitelistingGroups'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: ../../../common/v1/types.json#/definitions/CloudError
          description: Error response describing why the operation failed.
      tags:
        - applicationWhitelistings
      description: >-
        Gets a list of application control VM/server groups for the
        subscription.
      operationId: AdaptiveApplicationControls_List
      x-ms-examples:
        Gets a list of application control VM/server groups for the subscription:
          $ref: >-
            ./examples/ApplicationWhitelistings/GetApplicationWhitelistingsSubscription_example.json
  '/subscriptions/{subscriptionId}/providers/Microsoft.Security/locations/{ascLocation}/applicationWhitelistings/{groupName}':
    delete:
      parameters:
        - $ref: ../../../common/v1/types.json#/components/parameters/SubscriptionId
        - $ref: ../../../common/v1/types.json#/components/parameters/AscLocation
        - $ref: '#/components/parameters/GroupName'
        - $ref: ../../../common/v1/types.json#/components/parameters/ApiVersion
      responses:
        '200':
          description: >-
            OK - The response indicates that the delete operation completed
            successfully
        '202':
          description: >-
            Accepted. The response indicates the delete operation is performed
            in the background.
        '204':
          description: No Content. The response indicates the resource is already deleted.
        default:
          content:
            application/json:
              schema:
                $ref: ../../../common/v1/types.json#/definitions/CloudError
          description: Error response describing why the operation failed.
      tags:
        - applicationWhitelistings
      description: Delete an application control VM/server group
      operationId: AdaptiveApplicationControls_Delete
      x-ms-examples:
        Delete an application control VM/server group:
          $ref: >-
            ./examples/ApplicationWhitelistings/DeleteApplicationWhitelistings_example.json
    get:
      parameters:
        - $ref: ../../../common/v1/types.json#/components/parameters/SubscriptionId
        - $ref: ../../../common/v1/types.json#/components/parameters/AscLocation
        - $ref: '#/components/parameters/GroupName'
        - $ref: ../../../common/v1/types.json#/components/parameters/ApiVersion
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppWhitelistingGroup'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: ../../../common/v1/types.json#/definitions/CloudError
          description: Error response describing why the operation failed.
      tags:
        - applicationWhitelistings
      description: Gets an application control VM/server group.
      operationId: AdaptiveApplicationControls_Get
      x-ms-examples:
        Gets a configured application control VM/server group:
          $ref: >-
            ./examples/ApplicationWhitelistings/GetApplicationWhitelistingsGroup_example.json
    put:
      parameters:
        - $ref: ../../../common/v1/types.json#/components/parameters/SubscriptionId
        - $ref: ../../../common/v1/types.json#/components/parameters/AscLocation
        - $ref: '#/components/parameters/GroupName'
        - $ref: ../../../common/v1/types.json#/components/parameters/ApiVersion
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppWhitelistingGroup'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: ../../../common/v1/types.json#/definitions/CloudError
          description: Error response describing why the operation failed.
      tags:
        - applicationWhitelistings
      description: Update an application control VM/server group
      operationId: AdaptiveApplicationControls_Put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppWhitelistingPutGroupData'
        description: The updated VM/server group data
        required: true
      x-ms-examples:
        Update an application control VM/server group by adding a new file:
          $ref: >-
            ./examples/ApplicationWhitelistings/PutApplicationWhitelistings_example.json
components:
  parameters:
    GroupName:
      description: Name of an application control VM/server group
      in: path
      name: groupName
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    IncludePathRecommendations:
      description: Include the policy rules
      in: query
      name: includePathRecommendations
      required: false
      schema:
        enum:
          - false
          - true
        type: boolean
      x-ms-parameter-location: method
    Summary:
      description: Return output in a summarized form
      in: query
      name: summary
      required: false
      schema:
        enum:
          - false
          - true
        type: boolean
      x-ms-parameter-location: method
  schemas:
    AppWhitelistingGroup:
      allOf:
        - $ref: ../../../common/v1/types.json#/definitions/Resource
        - $ref: ../../../common/v1/types.json#/definitions/Location
      properties:
        properties:
          $ref: '#/components/schemas/AppWhitelistingGroupData'
          x-ms-client-flatten: true
      required:
        - properties
      type: object
    AppWhitelistingGroupData:
      description: >-
        Represents a VM/server group and set of rules that are Recommended by
        Microsoft Defender for Cloud to be allowed
      properties:
        configurationStatus:
          $ref: '#/components/schemas/ConfigurationStatus'
        enforcementMode:
          $ref: '#/components/schemas/EnforcementMode'
        issues:
          $ref: '#/components/schemas/AppWhitelistingIssuesSummaries'
        pathRecommendations:
          $ref: '#/components/schemas/PathRecommendations'
        protectionMode:
          $ref: '#/components/schemas/ProtectionMode'
        recommendationStatus:
          $ref: '#/components/schemas/RecommendationStatus'
        sourceSystem:
          $ref: '#/components/schemas/SourceSystem'
        vmRecommendations:
          $ref: '#/components/schemas/VmRecommendations'
      type: object
    AppWhitelistingGroups:
      description: >-
        Represents a list of VM/server groups and set of rules that are
        Recommended by Microsoft Defender for Cloud to be allowed
      properties:
        value:
          items:
            $ref: '#/components/schemas/AppWhitelistingGroup'
          type: array
      type: object
    AppWhitelistingIssue:
      description: An alert that VMs/servers within a group can have
      enum:
        - ViolationsAudited
        - ViolationsBlocked
        - MsiAndScriptViolationsAudited
        - MsiAndScriptViolationsBlocked
        - ExecutableViolationsAudited
        - RulesViolatedManually
      type: string
    AppWhitelistingIssueSummary:
      description: Represents a summary of the alerts of the VM/server group
      properties:
        issue:
          $ref: '#/components/schemas/AppWhitelistingIssue'
        numberOfVms:
          description: The number of machines in the VM/server group that have this alert
          type: number
      type: object
    AppWhitelistingIssuesSummaries:
      items:
        $ref: '#/components/schemas/AppWhitelistingIssueSummary'
      type: array
    AppWhitelistingPutGroupData:
      description: The altered data of the recommended VM/server group policy
      properties:
        enforcementMode:
          $ref: '#/components/schemas/EnforcementMode'
          description: >-
            The enforcement mode of the group. Can also be defined per
            collection type by using ProtectionMode
        pathRecommendations:
          $ref: '#/components/schemas/PathRecommendations'
        protectionMode:
          $ref: '#/components/schemas/ProtectionMode'
          description: >-
            The protection mode of the group per collection type. Can also be
            defined for all collection types by using EnforcementMode
        vmRecommendations:
          $ref: '#/components/schemas/VmRecommendations'
      type: object
    AppWhitelistingResourceType:
      description: The resource type of the application control resources
      example: Microsoft.Security/applicationWhitelistings
      type: string
    ConfigurationStatus:
      description: >-
        The configuration status of the VM/server group or machine or rule on
        the machine
      enum:
        - Configured
        - NotConfigured
        - InProgress
        - Failed
        - NoStatus
      type: string
    EnforcementMode:
      description: >-
        The application control policy enforcement/protection mode of the
        VM/server group
      enum:
        - Audit
        - Enforce
        - None
      type: string
    EnforcementSupport:
      description: The VM/server supportability of Enforce feature
      enum:
        - Supported
        - NotSupported
        - Unknown
      type: string
    FileType:
      description: The type of the file (for Linux files - Executable is used)
      enum:
        - Exe
        - Dll
        - Msi
        - Script
        - Executable
        - Unknown
      type: string
    GroupResourceId:
      description: The azure resource id of the application control VM/server group
      example: >-
        /subscriptions/12345678-1234-1234-1234-123456789123/providers/Microsoft.Security/applicationWhitelistings/GROUP1
      type: string
    PathRecommendation:
      description: Represents a path that is recommended to be allowed and its properties
      properties:
        action:
          $ref: '#/components/schemas/RecommendationAction'
        common:
          description: Whether the path is commonly run on the machine
          type: boolean
        configurationStatus:
          $ref: '#/components/schemas/ConfigurationStatus'
        fileType:
          $ref: '#/components/schemas/FileType'
        path:
          description: The full path to the application to allow
          example: 'C:\Windows\System32\calc.exe'
          type: string
        publisherInfo:
          $ref: '#/components/schemas/PublisherInfo'
        type:
          $ref: '#/components/schemas/RecommendationType'
        userSids:
          items:
            description: A security identifier
            example: S-1-5-18
            type: string
          type: array
        usernames:
          items:
            $ref: '#/components/schemas/UserRecommendation'
          type: array
      type: object
    PathRecommendations:
      items:
        $ref: '#/components/schemas/PathRecommendation'
      type: array
    ProtectionMode:
      description: >-
        The protection mode of the collection/file types. Exe/Msi/Script are
        used for Windows, Executable is used for Linux.
      properties:
        exe:
          $ref: '#/components/schemas/EnforcementMode'
        executable:
          $ref: '#/components/schemas/EnforcementMode'
        msi:
          $ref: '#/components/schemas/EnforcementMode'
        script:
          $ref: '#/components/schemas/EnforcementMode'
      type: object
    PublisherInfo:
      description: Represents the publisher information of a process/rule
      properties:
        binaryName:
          description: The "OriginalName" field taken from the file's version resource
          example: CHROME.EXE
          type: string
        productName:
          description: The product name taken from the file's version resource
          example: GOOGLE CHROME
          type: string
        publisherName:
          description: >-
            The Subject field of the x.509 certificate used to sign the code,
            using the following fields -  O = Organization, L = Locality, S =
            State or Province, and C = Country
          example: 'O=GOOGLE INC, L=MOUNTAIN VIEW, S=CALIFORNIA, C=US'
          type: string
        version:
          description: The binary file version taken from the file's version resource
          example: 66.0.3359.139
          type: string
      type: object
    RecommendationAction:
      description: The recommendation action of the VM/server or rule
      enum:
        - Recommended
        - Add
        - Remove
      type: string
    RecommendationStatus:
      description: The recommendation status of the VM/server group or VM/server
      enum:
        - Recommended
        - NotRecommended
        - NotAvailable
        - NoStatus
      type: string
    RecommendationType:
      description: The type of the rule to be allowed
      enum:
        - File
        - FileHash
        - PublisherSignature
        - ProductSignature
        - BinarySignature
        - VersionAndAboveSignature
      type: string
    SourceSystem:
      description: The source type of the VM/server group
      enum:
        - Azure_AppLocker
        - Azure_AuditD
        - NonAzure_AppLocker
        - NonAzure_AuditD
        - None
      type: string
    UserRecommendation:
      description: Represents a user that is recommended to be allowed for a certain rule
      properties:
        recommendationAction:
          $ref: '#/components/schemas/RecommendationAction'
        username:
          description: >-
            Represents a user that is recommended to be allowed for a certain
            rule
          example: LOCAL SYSTEM
          type: string
      type: object
    VmRecommendation:
      description: Represents a machine that is part of a VM/server group
      properties:
        configurationStatus:
          $ref: '#/components/schemas/ConfigurationStatus'
        enforcementSupport:
          $ref: '#/components/schemas/EnforcementSupport'
        recommendationAction:
          $ref: '#/components/schemas/RecommendationAction'
        resourceId:
          $ref: '#/components/schemas/VmResourceId'
      type: object
    VmRecommendations:
      items:
        $ref: '#/components/schemas/VmRecommendation'
      type: array
    VmResourceId:
      description: The full azure resource id of the machine
      example: >-
        /subscriptions/12345678-1234-1234-1234-123456789123/resourcegroups/group/providers/microsoft.compute/virtualmachines/vm
      type: string
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      flows:
        implicit:
          authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/authorize'
          scopes:
            user_impersonation: impersonate your user account
      type: oauth2
security:
  - azure_auth:
      - user_impersonation

