openapi: 3.0.0
info:
  description: >-
    Use these REST APIs for performing operations on Quota entity associated
    with your Azure API Management deployment. To configure call rate limit and
    quota policies refer to [how to configure call rate limit and
    quota](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-product-with-rules#a-namepolicies-ato-configure-call-rate-limit-and-quota-policies).
  title: ApiManagementClient
  version: '2017-03-01'
servers:
  - url: '{apimBaseUrl}'
    variables:
      apimBaseUrl:
        default: ''
        description: >-
          The management endpoint of the API Management service, for example
          https://myapimservice.management.azure-api.net.
        x-ms-skip-url-encoding: true
paths:
  '/quotas/{quotaCounterKey}':
    get:
      parameters:
        - $ref: '#/components/parameters/QuotaCounterKeyParameter'
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuotaCounterCollection'
          description: Lists a collection of the quota counter values.
        default:
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - QuotaByCounterKeys
      externalDocs:
        description: Document describing how to configure the quota policies.
        url: >-
          https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-product-with-rules#a-namepolicies-ato-configure-call-rate-limit-and-quota-policies
      description: >-
        Lists a collection of current quota counter periods associated with the
        counter-key configured in the policy on the specified service instance.
        The api does not support paging yet.
      operationId: QuotaByCounterKeys_List
      x-ms-examples:
        ApiManagementGetQuotas:
          $ref: ./examples/ApiManagementGetQuotas.json
    patch:
      parameters:
        - $ref: '#/components/parameters/QuotaCounterKeyParameter'
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        '204':
          description: Quota counter period was successfully updated.
        default:
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - QuotaByCounterKeys
      description: >-
        Updates all the quota counter values specified with the existing quota
        counter key to a value in the specified service instance. This should be
        used for reset of the quota counter values.
      operationId: QuotaByCounterKeys_Update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuotaCounterValueContractProperties'
        description: >-
          The value of the quota counter to be applied to all quota counter
          periods.
        required: true
      x-ms-examples:
        ApiManagementPatchQuotas:
          $ref: ./examples/ApiManagementPatchQuotas.json
  '/quotas/{quotaCounterKey}/{quotaPeriodKey}':
    get:
      parameters:
        - $ref: '#/components/parameters/QuotaCounterKeyParameter'
        - $ref: '#/components/parameters/QuotaPeriodKeyParameter'
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuotaCounterContract'
          description: >-
            The response body contains the Quota counter details for the
            specified period.
        default:
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - QuotaByPeriodKeys
      externalDocs:
        description: Document describing how to configure the quota policies.
        url: >-
          https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-product-with-rules#a-namepolicies-ato-configure-call-rate-limit-and-quota-policies
      description: >-
        Gets the value of the quota counter associated with the counter-key in
        the policy for the specific period in service instance.
      operationId: QuotaByPeriodKeys_Get
      x-ms-examples:
        ApiManagementGetQuotasByQuotaPeriod:
          $ref: ./examples/ApiManagementGetQuotasByQuotaPeriod.json
    patch:
      parameters:
        - $ref: '#/components/parameters/QuotaCounterKeyParameter'
        - $ref: '#/components/parameters/QuotaPeriodKeyParameter'
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        '204':
          description: The quota counter value was successfully updated.
        default:
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
          description: Error response describing why the operation failed.
      tags:
        - QuotaByPeriodKeys
      description: >-
        Updates an existing quota counter value in the specified service
        instance.
      operationId: QuotaByPeriodKeys_Update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuotaCounterValueContractProperties'
        description: The value of the Quota counter to be applied on the specified period.
        required: true
      x-ms-examples:
        ApiManagementPatchQuotasByQuotaPeriod:
          $ref: ./examples/ApiManagementPatchQuotasByQuotaPeriod.json
components:
  parameters:
    QuotaCounterKeyParameter:
      description: >-
        Quota counter key identifier.This is the result of expression defined in
        counter-key attribute of the quota-by-key policy.For Example, if you
        specify counter-key="boo" in the policy, then it’s accessible by "boo"
        counter key. But if it’s defined as counter-key="@("b"+"a")" then it
        will be accessible by "ba" key
      in: path
      name: quotaCounterKey
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    QuotaPeriodKeyParameter:
      description: Quota period key identifier.
      in: path
      name: quotaPeriodKey
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
  schemas:
    QuotaCounterCollection:
      description: Paged Quota Counter list representation.
      properties:
        count:
          description: Total record count number across all pages.
          format: int64
          type: integer
        nextLink:
          description: Next page link if any.
          type: string
        value:
          description: Quota counter values.
          items:
            $ref: '#/components/schemas/QuotaCounterContract'
          type: array
      type: object
    QuotaCounterContract:
      description: Quota counter details.
      properties:
        Value:
          $ref: '#/components/schemas/QuotaCounterValueContractProperties'
          description: Quota Value Properties
        counterKey:
          description: The Key value of the Counter. Must not be empty.
          minLength: 1
          type: string
        periodEndTime:
          description: >
            The date of the end of Counter Period. The date conforms to the
            following format: `yyyy-MM-ddTHH:mm:ssZ` as specified by the ISO
            8601 standard.
          format: date-time
          type: string
        periodKey:
          description: >-
            Identifier of the Period for which the counter was collected. Must
            not be empty.
          minLength: 1
          type: string
        periodStartTime:
          description: >
            The date of the start of Counter Period. The date conforms to the
            following format: `yyyy-MM-ddTHH:mm:ssZ` as specified by the ISO
            8601 standard.
          format: date-time
          type: string
      required:
        - counterKey
        - periodKey
        - periodStartTime
        - periodEndTime
      type: object
    QuotaCounterValueContract:
      description: Quota counter value details.
      properties:
        value:
          $ref: '#/components/schemas/QuotaCounterValueContractProperties'
          description: Quota counter Value Properties.
          x-ms-client-flatten: true
      type: object
    QuotaCounterValueContractProperties:
      description: Quota counter value details.
      properties:
        callsCount:
          description: Number of times Counter was called.
          format: int32
          type: integer
        kbTransferred:
          description: Data Transferred in KiloBytes.
          format: double
          type: number
      type: object
  securitySchemes:
    apim_key:
      in: header
      name: Authorization
      type: apiKey
security:
  - apim_key: []

