name: Generate Arazzo Specification for Jentic OpenAPI
description: Request automatic generation of an Arazzo specification from an Jentic OpenAPI URL
title: "[AUTO] Generate Arazzo spec for Jentic OpenAPI"
labels: [arazzo-generation]
body:
  - type: input
    id: openapi_url
    attributes:
      label: OpenAPI Specification URL
      description: |
        IMPORTANT: Please provide the RAW URL to the OpenAPI specification.

        For GitHub repositories:
        - ✅ CORRECT: https://raw.githubusercontent.com/jentic/jentic-public-apis/refs/heads/main/apis/openapi/vendor.com/api/version/openapi.json
        - ❌ INCORRECT: https://github.com/jentic/jentic-public-apis/blob/main/apis/openapi/vendor.com/api/version/openapi.json

        The URL should point directly to the JSON file in the Jentic Public API Repository, not to the GitHub web UI page.
      placeholder: "https://raw.githubusercontent.com/jentic/jentic-public-apis/refs/heads/main/apis/openapi/vendor.com/api/version/openapi.json"
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: "Optional: Add any additional context about this API that might be helpful"
      placeholder: "Any additional context about this API that might be helpful..."
    validations:
      required: false

  - type: textarea
    id: workflow_descriptions
    attributes:
      label: Request Workflow Descriptions
      description: |
        If you would like to request specific workflows, please add them as bullet points below under this section. Each bullet should describe a workflow you want generated from the OpenAPI specification. For example:

        - Create a new user and assign them a role
        - Authenticate a user and fetch their profile
        - Submit an order and retrieve order status

        If no workflows are specified, the generator will attempt to discover workflows automatically.
      placeholder: |
        - Create a new user and assign them a role
        - Authenticate a user and fetch their profile
        - Submit an order and retrieve order status
    validations:
      required: false
