openapi: 3.0.0
info:
  description: >-
    The Azure management API provides a RESTful set of web services that
    interact with Azure Key Vault.
  title: KeyVaultManagementClient
  version: '2015-06-01'
servers:
  - url: 'https://management.azure.com/'
paths:
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.KeyVault/vaults':
    get:
      parameters:
        - description: The name of the Resource Group to which the vault belongs.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
        - description: Maximum number of results to return.
          in: query
          name: $top
          schema:
            format: int32
            type: integer
        - $ref: '#/components/parameters/ApiVersionParameter'
        - $ref: '#/components/parameters/SubscriptionIdParameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VaultListResult'
          description: >-
            Get information about all key vaults in the specified resource
            group.
      tags:
        - Vaults
      description: >-
        The List operation gets information about the vaults associated with the
        subscription and within the specified resource group.
      operationId: Vaults_ListByResourceGroup
      x-ms-pageable:
        nextLinkName: nextLink
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.KeyVault/vaults/{vaultName}':
    delete:
      parameters:
        - description: The name of the Resource Group to which the vault belongs.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
        - description: The name of the vault to delete
          in: path
          name: vaultName
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/ApiVersionParameter'
        - $ref: '#/components/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK Response.
        '204':
          description: No Content.
      tags:
        - Vaults
      description: Deletes the specified Azure key vault.
      operationId: Vaults_Delete
    get:
      parameters:
        - description: The name of the Resource Group to which the vault belongs.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
        - description: The name of the vault.
          in: path
          name: vaultName
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/ApiVersionParameter'
        - $ref: '#/components/parameters/SubscriptionIdParameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vault'
          description: Retrieved vault
      tags:
        - Vaults
      description: Gets the specified Azure key vault.
      operationId: Vaults_Get
    put:
      parameters:
        - description: The name of the Resource Group to which the server belongs.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
        - description: Name of the vault
          in: path
          name: vaultName
          required: true
          schema:
            pattern: '^[a-zA-Z0-9-]{3,24}$'
            type: string
        - $ref: '#/components/parameters/ApiVersionParameter'
        - $ref: '#/components/parameters/SubscriptionIdParameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vault'
          description: Created or updated vault
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vault'
          description: Created or updated vault
      tags:
        - Vaults
      description: Create or update a key vault in the specified subscription.
      operationId: Vaults_CreateOrUpdate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VaultCreateOrUpdateParameters'
        description: Parameters to create or update the vault
        required: true
  '/subscriptions/{subscriptionId}/resources':
    get:
      parameters:
        - description: The filter to apply on the operation.
          in: query
          name: $filter
          required: true
          schema:
            enum:
              - resourceType eq 'Microsoft.KeyVault/vaults'
            type: string
        - description: Maximum number of results to return.
          in: query
          name: $top
          schema:
            format: int32
            type: integer
        - description: Azure Resource Manager Api Version.
          in: query
          name: api-version
          required: true
          schema:
            enum:
              - '2015-11-01'
            type: string
          x-ms-api-version: false
        - $ref: '#/components/parameters/SubscriptionIdParameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceListResult'
          description: Get information about all key vaults in the subscription.
      tags:
        - Vaults
      description: >-
        The List operation gets information about the vaults associated with the
        subscription.
      operationId: Vaults_List
      x-ms-pageable:
        nextLinkName: nextLink
components:
  parameters:
    ApiVersionParameter:
      description: Client Api Version.
      in: query
      name: api-version
      required: true
      schema:
        type: string
    SubscriptionIdParameter:
      description: >-
        Gets subscription credentials which uniquely identify Microsoft Azure
        subscription. The subscription ID forms part of the URI for every
        service call.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
  schemas:
    AccessPolicyEntry:
      description: >-
        An identity that have access to the key vault. All identities in the
        array must use the same tenant ID as the key vault's tenant ID.
      properties:
        applicationId:
          description: ' Application ID of the client making request on behalf of a principal'
          format: uuid
          type: string
        objectId:
          description: >-
            The object ID of a user, service principal or security group in the
            Azure Active Directory tenant for the vault. The object ID must be
            unique for the list of access policies.
          type: string
        permissions:
          $ref: '#/components/schemas/Permissions'
          description: 'Permissions the identity has for keys, secrets and certificates.'
        tenantId:
          description: >-
            The Azure Active Directory tenant ID that should be used for
            authenticating requests to the key vault.
          format: uuid
          type: string
      required:
        - tenantId
        - objectId
        - permissions
      type: object
    Permissions:
      description: 'Permissions the identity has for keys, secrets and certificates.'
      properties:
        certificates:
          description: Permissions to certificates
          items:
            enum:
              - all
              - get
              - list
              - delete
              - create
              - import
              - update
              - managecontacts
              - getissuers
              - listissuers
              - setissuers
              - deleteissuers
              - manageissuers
              - recover
              - purge
            type: string
            x-ms-enum:
              modelAsString: true
              name: CertificatePermissions
          type: array
        keys:
          description: Permissions to keys
          items:
            enum:
              - all
              - encrypt
              - decrypt
              - wrapKey
              - unwrapKey
              - sign
              - verify
              - get
              - list
              - create
              - update
              - import
              - delete
              - backup
              - restore
              - recover
              - purge
            type: string
            x-ms-enum:
              modelAsString: true
              name: KeyPermissions
          type: array
        secrets:
          description: Permissions to secrets
          items:
            enum:
              - all
              - get
              - list
              - set
              - delete
              - backup
              - restore
              - recover
              - purge
            type: string
            x-ms-enum:
              modelAsString: true
              name: SecretPermissions
          type: array
      type: object
    Resource:
      description: Key Vault resource
      properties:
        tags:
          additionalProperties:
            type: string
          description: 'The tags that will be assigned to the key vault. '
          type: object
        id:
          description: The Azure Resource Manager resource ID for the key vault.
          readOnly: true
          type: string
        location:
          description: The supported Azure location where the key vault should be created.
          type: string
        name:
          description: The name of the key vault.
          type: string
        type:
          description: The resource type of the key vault.
          readOnly: true
          type: string
      required:
        - location
        - name
      type: object
      x-ms-azure-resource: true
    ResourceListResult:
      description: List of vault resources.
      properties:
        nextLink:
          description: Gets the URL to get the next set of vault resources.
          type: string
        value:
          description: Gets the list of vault resources.
          items:
            $ref: '#/components/schemas/Resource'
          type: array
      type: object
    Sku:
      description: SKU details
      properties:
        family:
          description: SKU family name
          enum:
            - A
          type: string
          x-ms-client-default: A
          x-ms-enum:
            modelAsString: true
            name: SkuFamily
        name:
          description: >-
            SKU name to specify whether the key vault is a standard vault or a
            premium vault.
          enum:
            - standard
            - premium
          type: string
          x-ms-enum:
            modelAsString: false
            name: SkuName
      required:
        - name
        - family
      type: object
    Vault:
      allOf:
        - $ref: '#/components/schemas/Resource'
      description: Resource information with extended details.
      properties:
        properties:
          $ref: '#/components/schemas/VaultProperties'
          description: Properties of the vault
      required:
        - properties
      type: object
    VaultCreateOrUpdateParameters:
      description: Parameters for creating or updating a vault
      properties:
        tags:
          additionalProperties:
            type: string
          description: 'The tags that will be assigned to the key vault. '
          type: object
        location:
          description: The supported Azure location where the key vault should be created.
          type: string
        properties:
          $ref: '#/components/schemas/VaultProperties'
          description: Properties of the vault
      required:
        - location
        - properties
      type: object
      x-ms-azure-resource: true
    VaultListResult:
      description: List of vaults
      properties:
        nextLink:
          description: Gets or sets the URL to get the next set of vaults.
          type: string
        value:
          description: Gets or sets the list of vaults.
          items:
            $ref: '#/components/schemas/Vault'
          type: array
      type: object
    VaultProperties:
      description: Properties of the vault
      properties:
        accessPolicies:
          description: >-
            An array of 0 to 16 identities that have access to the key vault.
            All identities in the array must use the same tenant ID as the key
            vault's tenant ID.
          items:
            $ref: '#/components/schemas/AccessPolicyEntry'
          maxItems: 16
          type: array
        enableSoftDelete:
          description: >-
            Property to specify whether the 'soft delete' functionality is
            enabled for this key vault.
          type: boolean
        enabledForDeployment:
          description: >-
            Property to specify whether Azure Virtual Machines are permitted to
            retrieve certificates stored as secrets from the key vault.
          type: boolean
        enabledForDiskEncryption:
          description: >-
            Property to specify whether Azure Disk Encryption is permitted to
            retrieve secrets from the vault and unwrap keys.
          type: boolean
        enabledForTemplateDeployment:
          description: >-
            Property to specify whether Azure Resource Manager is permitted to
            retrieve secrets from the key vault.
          type: boolean
        sku:
          $ref: '#/components/schemas/Sku'
          description: SKU details
        tenantId:
          description: >-
            The Azure Active Directory tenant ID that should be used for
            authenticating requests to the key vault.
          format: uuid
          type: string
        vaultUri:
          description: The URI of the vault for performing operations on keys and secrets.
          type: string
      required:
        - tenantId
        - sku
        - accessPolicies
      type: object

