openapi: 3.0.0
info:
  title: TrapStreet API
  version: 1.0.0
  description: The TrapStreet API finds trap streets in Google Maps, Bing Maps and OpenStreetMap data.
  contact:
    name: John Swanson
servers:
  - url: https://api.trapstreet.com
paths:
  /{address}:
    get:
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                properties:
                  trap:
                    type: boolean
                  description:
                    type: string