openapi: 3.0.0
info:
  title: PredictionEndpoint
  version: '1.1'
servers:
  - url: >-
      https://southcentralus.api.cognitive.microsoft.com/customvision/v1.1/Prediction
paths:
  '/{projectId}/image':
    post:
      parameters:
        - description: The project id
          in: path
          name: projectId
          required: true
          schema:
            format: uuid
            type: string
          x-nullable: false
        - description: "Optional. Specifies the id of a particular iteration to evaluate against.\r\n            The default iteration for the project will be used when not specified"
          in: query
          name: iterationId
          required: false
          schema:
            format: uuid
            type: string
          x-nullable: true
        - description: Optional. Specifies the name of application using the endpoint
          in: query
          name: application
          required: false
          schema:
            type: string
          x-nullable: true
        - $ref: '#/components/parameters/ApiKey'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
          description: OK
      tags:
        - ImagePredictionApi
      operationId: PredictImage
      requestBody:
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
        required: true
      summary: Predict an image and saves the result
      x-ms-examples:
        Successful Prediction with Image request:
          $ref: ./examples/SuccessfulPredictionWithImage.json
  '/{projectId}/image/nostore':
    post:
      parameters:
        - description: The project id
          in: path
          name: projectId
          required: true
          schema:
            format: uuid
            type: string
          x-nullable: false
        - description: "Optional. Specifies the id of a particular iteration to evaluate against.\r\n            The default iteration for the project will be used when not specified"
          in: query
          name: iterationId
          required: false
          schema:
            format: uuid
            type: string
          x-nullable: true
        - description: Optional. Specifies the name of application using the endpoint
          in: query
          name: application
          required: false
          schema:
            type: string
          x-nullable: true
        - $ref: '#/components/parameters/ApiKey'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
          description: OK
      tags:
        - ImagePredictionApi
      operationId: PredictImageWithNoStore
      requestBody:
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
        required: true
      summary: Predict an image without saving the result
      x-ms-examples:
        Successful Prediction with Image request:
          $ref: ./examples/SuccessfulPredictionWithImage.json
  '/{projectId}/url':
    post:
      parameters:
        - description: The project id
          in: path
          name: projectId
          required: true
          schema:
            format: uuid
            type: string
          x-nullable: false
        - description: "Optional. Specifies the id of a particular iteration to evaluate against.\r\n            The default iteration for the project will be used when not specified"
          in: query
          name: iterationId
          required: false
          schema:
            format: uuid
            type: string
          x-nullable: true
        - description: Optional. Specifies the name of application using the endpoint
          in: query
          name: application
          required: false
          schema:
            type: string
          x-nullable: true
        - $ref: '#/components/parameters/ApiKey'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
          description: OK
      tags:
        - ImagePredictionApi
      operationId: PredictImageUrl
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageUrl'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ImageUrl'
          application/xml:
            schema:
              $ref: '#/components/schemas/ImageUrl'
          text/json:
            schema:
              $ref: '#/components/schemas/ImageUrl'
          text/xml:
            schema:
              $ref: '#/components/schemas/ImageUrl'
        description: >-
          An {Iris.Web.Api.Models.ImageUrl} that contains the url of the image
          to be evaluated
        required: true
      summary: Predict an image url and saves the result
      x-ms-examples:
        Successful Prediction with Url request:
          $ref: ./examples/SuccessfulPredictionWithUrl.json
  '/{projectId}/url/nostore':
    post:
      parameters:
        - description: The project id
          in: path
          name: projectId
          required: true
          schema:
            format: uuid
            type: string
          x-nullable: false
        - description: "Optional. Specifies the id of a particular iteration to evaluate against.\r\n            The default iteration for the project will be used when not specified"
          in: query
          name: iterationId
          required: false
          schema:
            format: uuid
            type: string
          x-nullable: true
        - description: Optional. Specifies the name of application using the endpoint
          in: query
          name: application
          required: false
          schema:
            type: string
          x-nullable: true
        - $ref: '#/components/parameters/ApiKey'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/ImagePredictionResultModel'
          description: OK
      tags:
        - ImagePredictionApi
      operationId: PredictImageUrlWithNoStore
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageUrl'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ImageUrl'
          application/xml:
            schema:
              $ref: '#/components/schemas/ImageUrl'
          text/json:
            schema:
              $ref: '#/components/schemas/ImageUrl'
          text/xml:
            schema:
              $ref: '#/components/schemas/ImageUrl'
        description: >-
          An {Iris.Web.Api.Models.ImageUrl} that contains the url of the image
          to be evaluated
        required: true
      summary: Predict an image url without saving the result
      x-ms-examples:
        Successful Prediction with Url request:
          $ref: ./examples/SuccessfulPredictionWithUrl.json
components:
  parameters:
    ApiKey:
      in: header
      name: Prediction-Key
      required: true
      schema:
        type: string
      x-ms-client-name: ApiKey
      x-ms-parameter-location: client
  requestBodies:
    ImageUrl:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ImageUrl'
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/components/schemas/ImageUrl'
        application/xml:
          schema:
            $ref: '#/components/schemas/ImageUrl'
        text/json:
          schema:
            $ref: '#/components/schemas/ImageUrl'
        text/xml:
          schema:
            $ref: '#/components/schemas/ImageUrl'
      description: >-
        An {Iris.Web.Api.Models.ImageUrl} that contains the url of the image to
        be evaluated
      required: true
    PredictImage:
      content:
        application/octet-stream:
          schema:
            format: binary
            type: string
      required: true
  schemas:
    ImagePredictionResultModel:
      description: result of an image prediction request
      nullable: true
      properties:
        Created:
          format: date-time
          nullable: false
          readOnly: true
          type: string
        Id:
          format: uuid
          nullable: false
          readOnly: true
          type: string
        Iteration:
          format: uuid
          nullable: false
          readOnly: true
          type: string
        Predictions:
          items:
            $ref: '#/components/schemas/ImageTagPredictionModel'
          nullable: true
          readOnly: true
          type: array
        Project:
          format: uuid
          nullable: false
          readOnly: true
          type: string
      type: object
    ImageTagPredictionModel:
      nullable: true
      properties:
        Probability:
          format: float
          nullable: false
          readOnly: true
          type: number
        Tag:
          nullable: true
          readOnly: true
          type: string
        TagId:
          format: uuid
          nullable: false
          readOnly: true
          type: string
      type: object
    ImageUrl:
      nullable: true
      properties:
        Url:
          nullable: true
          type: string
      type: object

