openapi: 3.0.0
info:
  description: >-
    The Microsoft Azure Network management API provides a RESTful set of web
    services that interact with Microsoft Azure Networks service to manage your
    network resources. The API has entities that capture the relationship
    between an end user and the Microsoft Azure Networks service.
  title: NetworkManagementClient
  version: '2019-04-01'
servers:
  - url: 'https://management.azure.com/'
paths:
  '/subscriptions/{subscriptionId}/providers/Microsoft.Network/applicationSecurityGroups':
    get:
      parameters:
        - $ref: ./network.json#/components/parameters/ApiVersionParameter
        - $ref: ./network.json#/components/parameters/SubscriptionIdParameter
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationSecurityGroupListResult'
          description: >-
            Request successful. The operation returns a list of application
            security group resources.
      tags:
        - ApplicationSecurityGroups
      description: Gets all application security groups in a subscription.
      operationId: ApplicationSecurityGroups_ListAll
      x-ms-examples:
        List all application security groups:
          $ref: ./examples/ApplicationSecurityGroupListAll.json
      x-ms-pageable:
        nextLinkName: nextLink
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/applicationSecurityGroups':
    get:
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
        - $ref: ./network.json#/components/parameters/ApiVersionParameter
        - $ref: ./network.json#/components/parameters/SubscriptionIdParameter
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationSecurityGroupListResult'
          description: >-
            Request successful. The operation returns a list of application
            security group resources.
      tags:
        - ApplicationSecurityGroups
      description: Gets all the application security groups in a resource group.
      operationId: ApplicationSecurityGroups_List
      x-ms-examples:
        List load balancers in resource group:
          $ref: ./examples/ApplicationSecurityGroupList.json
      x-ms-pageable:
        nextLinkName: nextLink
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/applicationSecurityGroups/{applicationSecurityGroupName}':
    delete:
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
        - description: The name of the application security group.
          in: path
          name: applicationSecurityGroupName
          required: true
          schema:
            type: string
        - $ref: ./network.json#/components/parameters/ApiVersionParameter
        - $ref: ./network.json#/components/parameters/SubscriptionIdParameter
      responses:
        '200':
          description: Delete successful.
        '202':
          description: Accepted and the operation will complete asynchronously.
        '204':
          description: Request successful. Resource does not exist.
      tags:
        - ApplicationSecurityGroups
      description: Deletes the specified application security group.
      operationId: ApplicationSecurityGroups_Delete
      x-ms-examples:
        Delete application security group:
          $ref: ./examples/ApplicationSecurityGroupDelete.json
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
    get:
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
        - description: The name of the application security group.
          in: path
          name: applicationSecurityGroupName
          required: true
          schema:
            type: string
        - $ref: ./network.json#/components/parameters/ApiVersionParameter
        - $ref: ./network.json#/components/parameters/SubscriptionIdParameter
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationSecurityGroup'
          description: >-
            Request successful. The operation returns the specified application
            security group resource.
      tags:
        - ApplicationSecurityGroups
      description: Gets information about the specified application security group.
      operationId: ApplicationSecurityGroups_Get
      x-ms-examples:
        Get application security group:
          $ref: ./examples/ApplicationSecurityGroupGet.json
    patch:
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
        - description: The name of the application security group.
          in: path
          name: applicationSecurityGroupName
          required: true
          schema:
            type: string
        - $ref: ./network.json#/components/parameters/ApiVersionParameter
        - $ref: ./network.json#/components/parameters/SubscriptionIdParameter
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationSecurityGroup'
          description: >-
            Update successful. The operation returns the resulting
            ApplicationSecurityGroup resource.
      tags:
        - applicationSecurityGroups
      description: Updates an application security group's tags.
      operationId: ApplicationSecurityGroups_UpdateTags
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./network.json#/definitions/TagsObject
        description: Parameters supplied to update application security group tags.
        required: true
      x-ms-examples:
        Update application security group tags:
          $ref: ./examples/ApplicationSecurityGroupUpdateTags.json
      x-ms-long-running-operation: true
    put:
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
        - description: The name of the application security group.
          in: path
          name: applicationSecurityGroupName
          required: true
          schema:
            type: string
        - $ref: ./network.json#/components/parameters/ApiVersionParameter
        - $ref: ./network.json#/components/parameters/SubscriptionIdParameter
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationSecurityGroup'
          description: >-
            Update successful. The operation returns the resulting application
            security group resource.
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationSecurityGroup'
          description: >-
            Create successful. The operation returns the resulting application
            security group resource.
      tags:
        - ApplicationSecurityGroups
      description: Creates or updates an application security group.
      operationId: ApplicationSecurityGroups_CreateOrUpdate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationSecurityGroup'
        description: >-
          Parameters supplied to the create or update ApplicationSecurityGroup
          operation.
        required: true
      x-ms-examples:
        Create application security group:
          $ref: ./examples/ApplicationSecurityGroupCreate.json
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
components:
  schemas:
    ApplicationSecurityGroup:
      allOf:
        - $ref: ./network.json#/definitions/Resource
      description: An application security group in a resource group.
      properties:
        etag:
          description: >-
            A unique read-only string that changes whenever the resource is
            updated.
          readOnly: true
          type: string
        properties:
          $ref: '#/components/schemas/ApplicationSecurityGroupPropertiesFormat'
          description: Properties of the application security group.
          x-ms-client-flatten: true
      type: object
    ApplicationSecurityGroupListResult:
      description: A list of application security groups.
      properties:
        nextLink:
          description: The URL to get the next set of results.
          readOnly: true
          type: string
        value:
          description: A list of application security groups.
          items:
            $ref: '#/components/schemas/ApplicationSecurityGroup'
          type: array
      type: object
    ApplicationSecurityGroupPropertiesFormat:
      description: Application security group properties.
      properties:
        provisioningState:
          description: >-
            The provisioning state of the application security group resource.
            Possible values are: 'Succeeded', 'Updating', 'Deleting', and
            'Failed'.
          readOnly: true
          type: string
        resourceGuid:
          description: >-
            The resource GUID property of the application security group
            resource. It uniquely identifies a resource, even if the user
            changes its name or migrate the resource across subscriptions or
            resource groups.
          readOnly: true
          type: string
      type: object
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      flows:
        implicit:
          authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/authorize'
          scopes:
            user_impersonation: impersonate your user account
      type: oauth2
security:
  - azure_auth:
      - user_impersonation

